account/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url

urlpatterns = patterns('account.views',
    url(r'^login/$', 'account_login', name="account_login"),
    url(r'^logout/$', 'account_logout', name="account_logout"),
)

irpmemr/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:

    # # url(r'^irpmemr/', include('irpmemr.foo.urls')),
    # url(r'^admission/', 'irpmemr.views.admission', name='admission'),

    # url(r'^allpatients/', 'irpmemr.views.allpatients', name='allpatients'),

    # url(r'^addiinfo/(?P<pid>\w+)$', 'irpmemr.views.addiinfo', name='addiinfo'),

    # url(r'^medhis/(?P<pid>\w+)$', 'irpmemr.views.medhis', name='medhis'),

    # url(r'^routinecheckup/(?P<pid>\w+)$', 'irpmemr.views.routinecheckup', name='routinecheckup'),

    # url(r'^labtest/(?P<pid>\w+)$', 'irpmemr.views.labtest', name='labtest'),

    # url(r'^usscanning/(?P<pid>\w+)$', 'irpmemr.views.usscanning', name='usscanning'),

    # url(r'^notification$', 'irpmemr.views.notification', name='notification'),

    # url(r'^teleconsultation$', 'irpmemr.views.teleconsultation', name='teleconsultation'),

    # url(r'^setlogin$', 'irpmemr.views.setlogin', name='setlogin'),

    # url(r'^msg/add/$', 'irpmemr.views.addmessages', name='addmessages'),
    # url(r'^msg/show/$', 'irpmemr.views.showmessages', name='showmessages'),
    # url(r'^msg$', 'irpmemr.views.messages', name='messages'),

    url(r'^account/', include('account.urls')),
    url(r'^patient/', include('patient.urls')),
    url(r'^teleconsultation/', include('consultation.urls')),
    url(r'^notification/', include('notification.urls')),
    url(r'^$', 'irpmemr.views.home', name='home'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True,}),
)

urlpatterns += staticfiles_urlpatterns()

patient/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url

# from patient.views import FileUploadView

urlpatterns = patterns('patient.views',
    url(r'^visit/(?P<patient_id>\w+)/$', 'patient_visit', name="patient_visit"),
    url(r'^visit/add/(?P<patient_id>\w+)/$', 'patient_visit_add', name="patient_visit_add"),

    url(r'^admission/add/(?P<patient_id>\w+)/$', 'patient_admission_add', name="patient_admission_add"),
    url(r'^admission/view/(?P<patient_id>\w+)/(?P<admission_id>\w+)/$', 'patient_admission_add', name="patient_admission_view"),

    url(r'^basic-information/(?P<patient_id>\w+)/$', 'basic_patient_information', name="basic_patient_information"),
    url(r'^additional-details/(?P<patient_id>\w+)/$', 'additional_details', name="additional_details"),

    url(r'^medical-history/(?P<patient_id>\w+)/$', 'medical_history', name="medical_history"),
    url(r'^past-medical-history/(?P<patient_id>\w+)/$', 'past_medical_history', name="past_medical_history"),
    url(r'^menstrual-history/(?P<patient_id>\w+)/$', 'menstrual_history', name="menstrual_history"),
    url(r'^obstetric-history/(?P<patient_id>\w+)/$', 'obstetric_history', name="obstetric_history"),
    url(r'^obstetric-add/(?P<patient_id>\w+)/$', 'obstetric_add', name="obstetric_add"),
    url(r'^present-medical-history/(?P<patient_id>\w+)/$', 'present_medical_history', name="present_medical_history"),
    url(r'^gynaecological-history/(?P<patient_id>\w+)/$', 'gynaecological_history', name="gynaecological_history"),
    url(r'^immunization-history/(?P<patient_id>\w+)/$', 'immunization_history', name="immunization_history"),

    url(r'^routine-checkup/(?P<patient_id>\w+)/$', 'routine_checkup', name="routine_checkup"),
    url(r'^routine-checkup/add/(?P<patient_id>\w+)/$', 'routine_checkup_add', name="routine_checkup_add"),
    url(r'^routine-checkup/view/(?P<patient_id>\w+)/(?P<routine_id>\w+)/$', 'routine_checkup_add', name="routine_checkup_view"),

    url(r'^laboratory-test/(?P<patient_id>\w+)/$', 'laboratory_test', name="laboratory_test"),
    url(r'^laboratory-test/add/(?P<patient_id>\w+)/$', 'laboratory_test_add', name="laboratory_test_add"),
    url(r'^laboratory-test/view/(?P<patient_id>\w+)/(?P<lab_id>\w+)/$', 'laboratory_test_add', name="laboratory_test_view"),

    url(r'^ultrasound-scanning/(?P<patient_id>\w+)/$', 'ultrasound_scanning', name="ultrasound_scanning"),
    url(r'^ultrasound-scanning/add/(?P<patient_id>\w+)/$', 'ultrasound_scanning_add', name="ultrasound_scanning_add"),
    url(r'^ultrasound-scanning/view/(?P<patient_id>\w+)/(?P<us_id>\w+)/$', 'ultrasound_scanning_add', name="ultrasound_scanning_view"),
    url(r'^ultrasound-scanning/img-upload/$', 'upload_image', name="ultrasound_upload_image"),
    url(r'^ultrasound-scanning/img/(?P<img_id>\w+)/$', 'ultrasound_scanning_img', name="ultrasound_scanning_img"),

    url(r'^prescription/(?P<patient_id>\w+)/$', 'prescription', name="prescription"),
    url(r'^prescription/add/(?P<patient_id>\w+)/$', 'prescription_add', name="prescription_add"),
    url(r'^prescription/view/(?P<patient_id>\w+)/(?P<prs_id>\w+)/$', 'prescription_add', name="prescription_view"),

    url(r'^add/$', 'patient_add', name="patient_add"),
    url(r'^(?P<patient_id>\w+)/(?P<current_tab>\w+)/$', 'patient_info', name="patient_info_tab"),
    url(r'^(?P<patient_id>\w+)/$', 'patient_info', name="patient_info"),
    url(r'^$', 'patient_home', name="patient_home"),
)

# urlpatterns += patterns('',
#     (r'^us-upload/$', FileUploadView.as_view()),
# )

prescription/models.py
from django.db import models

# Create your models here.

patient/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.db.models import Q

from patient.models import PatientInformation, AdditionalPatientInformation, Guardian, \
    MedicalHistory, PastMedicalHistory, PresentMedicalHistory, FamilyMedicalHistory, \
    MenstrualHistory, ObstetricHistory, GynaecologicalHistory, ImmunizationHistory, \
    Routinecheckup, LaboratoryTest, UltrasoundScanning, Prescription, PreviousObstetricHistory, \
    PreviousSurgery

class SearchPatientForm(forms.Form):
    q = forms.CharField(label="Search", required=True)

    def results(self):
        """
        Filter the results from PatientInformation
        """
        q = self.cleaned_data['q'].strip()
        patients = PatientInformation.objects.filter(Q(operator__username__contains=q) | \
            Q(patient_id__contains=q) | Q(first_name__contains=q) | Q(last_name__contains=q) | \
            Q(email__contains=q)).distinct()
        return patients

class AddPatientForm(forms.ModelForm):
    """
    Form for add new patient
    """
    date_of_birth = forms.DateField(widget=forms.TextInput(attrs={'class':'datepicker'}))

    class Meta:
        model = PatientInformation

class PatientInformationForm(forms.ModelForm):
    """
    Form for view or edit patient info
    """
    date_of_birth = forms.DateField(widget=forms.TextInput(attrs={'class':'datepicker'}))

    class Meta:
        model = PatientInformation
        exclude = ('patient',)

class AdditionalPatientInformationForm(forms.ModelForm):
    """
    Form for view or edit additional patient info
    """
    # def __init__(self, patient=None, *args, **kwargs):
    #     super(AdditionalPatientInformationForm, self).__init__(*args, **kwargs)
    #     if patient:
    #         self.fields['patient'].initial = patient.id
    #         self.fields['patient'].widget.attrs['disabled'] = True

    class Meta:
        model = AdditionalPatientInformation
        exclude = ('patient',)

class GuardianForm(forms.ModelForm):
    """
    Form for view or edit guardian info
    """
    # def __init__(self, patient=None, *args, **kwargs):
    #     super(GuardianForm, self).__init__(*args, **kwargs)
    #     if patient:
    #         self.fields['patient'].initial = patient.id
    #         self.fields['patient'].widget.attrs['disabled'] = True

    class Meta:
        model = Guardian
        exclude = ('patient',)

class MedicalHistoryForm(forms.ModelForm):
    """
    form for MedicalHistory
    """
    class Meta:
        model = MedicalHistory
        exclude = ('patient',)

class PastMedicalHistoryForm(forms.ModelForm):
    """
    form for PastMedicalHistory
    """
    date = forms.DateField(widget=forms.TextInput(attrs={'class':'datepicker'}))

    class Meta:
        model = PastMedicalHistory
        exclude = ('patient',)

class PresentMedicalHistoryForm(forms.ModelForm):
    """
    form for PresentMedicalHistory
    """
    date = forms.DateField(widget=forms.TextInput(attrs={'class':'datepicker'}))
    class Meta:
        model = PresentMedicalHistory
        exclude = ('patient',)

class FamilyMedicalHistoryForm(forms.ModelForm):
    """
    form for FamilyMedicalHistory
    """
    date = forms.DateField(widget=forms.TextInput(attrs={'class':'datepicker'}))
    class Meta:
        model = FamilyMedicalHistory
        exclude = ('patient',)

class MenstrualHistoryForm(forms.ModelForm):
    """
    form for MenstrualHistory
    """
    day_of_visit = forms.DateField(widget=forms.TextInput(attrs={'class':'datepicker'}))
    last_menstrual_periods = forms.DateField(widget=forms.TextInput(attrs={'class':'datepicker'}))
    expected_date_of_delivery = forms.DateField(widget=forms.TextInput(attrs={'class':'datepicker'}))
    class Meta:
        model = MenstrualHistory
        exclude = ('patient',)

class ObstetricHistoryForm(forms.ModelForm):
    """
    form for ObstetricHistory
    """
    class Meta:
        model = ObstetricHistory
        exclude = ('patient',)

class PreviousObstetricHistoryForm(forms.ModelForm):
    """
    form for PreviousObstetricHistory
    """
    dob = forms.DateField(widget=forms.TextInput(attrs={'class':'datepicker'}))
    class Meta:
        model = PreviousObstetricHistory
        exclude = ('patient',)

class GynaecologicalHistoryForm(forms.ModelForm):
    """
    form for GynaecologicalHistory
    """
    date_of_last_pap_smear = forms.DateField(widget=forms.TextInput(attrs={'class':'datepicker'}))
    class Meta:
        model = GynaecologicalHistory
        exclude = ('patient', 'previous_surgery',)

class ImmunizationHistoryForm(forms.ModelForm):
    """
    form for ImmunizationHistory
    """
    tetanus_toxoid1 = forms.DateTimeField(label="First Injection", widget=forms.TextInput(attrs={'class':'datetimepicker'}), required=False)
    tetanus_toxoid2 = forms.DateTimeField(label="Second Injection", widget=forms.TextInput(attrs={'class':'null-date'}), required=False)
    tetanus_toxoid3 = forms.DateTimeField(label="Third Injection", widget=forms.TextInput(attrs={'class':'null-date'}), required=False)

    class Meta:
        model = ImmunizationHistory
        exclude = ('patient',)

    def __init__(self, *args, **kwargs):
        super(ImmunizationHistoryForm, self).__init__(*args, **kwargs)
        instance = kwargs.get('instance')
        if instance:
            for i in ['tetanus_toxoid2', 'tetanus_toxoid3']:
                if instance.__dict__.get(i):
                    self.fields[i].widget = forms.TextInput(attrs={'class':'datetimepicker'})

class RoutinecheckupForm(forms.ModelForm):
    """
    form for Routinecheckup
    """
    date = forms.DateField(widget=forms.TextInput(attrs={'class':'datepicker'}))
    class Meta:
        model = Routinecheckup
        exclude = ('patient',)

class LaboratoryTestForm(forms.ModelForm):
    """
    form for LaboratoryTest
    """
    date = forms.DateField(widget=forms.TextInput(attrs={'class':'datepicker'}))
    class Meta:
        model = LaboratoryTest
        exclude = ('patient',)

class UltrasoundScanningForm(forms.ModelForm):
    """
    form for UltrasoundScanning
    """
    date = forms.DateField(widget=forms.TextInput(attrs={'class':'datepicker'}))
    temp_img = forms.CharField(widget=forms.HiddenInput())
    class Meta:
        model = UltrasoundScanning
        exclude = ('patient',)

class PrescriptionForm(forms.ModelForm):
    """
    form for Prescription
    """
    date = forms.DateField(widget=forms.TextInput(attrs={'class':'datepicker'}))
    class Meta:
        model = Prescription
        exclude = ('patient',)

class PreviousSurgeryForm(forms.ModelForm):
    """
    form for PreviousSurgery
    """
    class Meta:
        model = PreviousSurgery
        exclude = ('patient',)

prescription/views.py
# Create your views here.

templates/patient/gynaecological_history.html
{% load i18n %}

<div id="form-wrapper">
    {% include "_inner_message.html" %}
    <form action="" method="POST" id="form-base">
        {% csrf_token %}
        <table class="table table-hover table-striped">
            <tr>
                <td {% if medical_tab == 'fmh' %}class="medical-active"{% endif %}><a class="medical-link" href="{% url 'medical_history' patient_id %}">Family Medical History</a></td>
                <td>
                </td>
            </tr>
            <tr>
                <td {% if medical_tab == 'pah' %}class="medical-active"{% endif %}><a class="medical-link" href="{% url 'past_medical_history' patient_id %}">Past Medical History</a></td>
                <td>
                </td>
            </tr>
            <tr>
                <td {% if medical_tab == 'meh' %}class="medical-active"{% endif %}><a class="medical-link" href="{% url 'menstrual_history' patient_id %}">Menstrual History</a></td>
                <td>
                </td>
            </tr>
            <tr>
                <td {% if medical_tab == 'obh' %}class="medical-active"{% endif %}><a class="medical-link" href="{% url 'obstetric_history' patient_id %}">Obstetric History</a></td>
                <td>
                </td>
            </tr>
            <tr>
                <td {% if medical_tab == 'prh' %}class="medical-active"{% endif %}><a class="medical-link" href="{% url 'present_medical_history' patient_id %}">Present Medical History</a></td>
                <td>
                </td>
            </tr>
            <tr>
                <td {% if medical_tab == 'gyh' %}class="medical-active"{% endif %}>Gynaecological History</td>
                <td>
                    <table class="table table-normal">
                        {% for f in form %}
                            <tr>
                                <td><label for="id_{{ f.name }}">{{ f.label }}</label></td>
                                <td colspan="2">{{ f }}
                                    <div class="control-group{% if f.errors %} error{% endif %}">
                                        {% if f.errors %}
                                            <span class="help-inline">{{ f.errors }}</span>
                                        {% endif %}
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                        <tr>
                            <td>Previous surgery</td>
                            <td colspan="2"></td>
                        </tr>
                        {% for f in form2 %}
                            <tr>
                                <td></td>
                                <td><label for="id_{{ f.name }}">{{ f.label }}</label></td>
                                <td>{{ f }}
                                    <div class="control-group{% if f.errors %} error{% endif %}">
                                        {% if f.errors %}
                                            <span class="help-inline">{{ f.errors }}</span>
                                        {% endif %}
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                        <tr>
                            <td></td>
                            <td class="text-center">
                                <button type="submit" class="btn btn-inverse">{% trans "Save" %} &nbsp;<i class="icon-ok icon-white"></i></button>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr>
                <td {% if medical_tab == 'imh' %}class="medical-active"{% endif %}><a class="medical-link" href="{% url 'immunization_history' patient_id %}">Immunization History</a></td>
                <td></td>
            </tr>
        </table>
    </form>

    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.simple-dtpicker.js"></script>
    <script type="text/javascript">
        $('#form-base').submit(function(e) {
            e.preventDefault();
            $.post("{% url 'gynaecological_history' patient_id %}", $("#form-base").serialize(), function(data) {
                $('#form-wrapper').html(data);
            });
        });
        $('*[class=datepicker]').appendDtpicker({"closeOnSelected": true, "dateOnly": true});
        $('.medical-link').click(function(e){
            e.preventDefault();
            $('#form-wrapper').load(this.getAttribute('href'));
        });
    </script>
</div>

templates/patient/laboratory_test_add.html
{% load i18n %}

<div id="form-wrapper">
    {% include "_inner_message.html" %}
    <form action="" method="POST" id="form-base">
        {% csrf_token %}
        <table class="table table-hover table-normal">
            {% for f in form %}
                {% include '_table_horizontal_field.html' with field=f %}
            {% endfor %}
            <tr>
                <td></td>
                <td class="text-center">
                    <button type="button" class="btn btn-primary" id="back-lab"><i class="icon-step-backward icon-white"></i> &nbsp;&nbsp;&nbsp;{% trans "Cancel" %}</button>
                    <button type="submit" class="btn btn-inverse">{% trans "Save" %} &nbsp;<i class="icon-ok icon-white"></i></button>
                </td>
            </tr>
        </table>
    </form>

    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.simple-dtpicker.js"></script>
    <script type="text/javascript">
        $('#form-base').submit(function(e) {
            e.preventDefault();
            {% if lab_id %}
            $.post("{% url 'laboratory_test_view' patient_id lab_id %}", $("#form-base").serialize(), function(data) {
                $('#form-wrapper').html(data);
            });
            {% else %}
            $.post("{% url 'laboratory_test_add' patient_id %}", $("#form-base").serialize(), function(data) {
                $('#form-wrapper').html(data);
            });
            {% endif %}
        });
        $('#back-lab').click(function(e) {
            e.preventDefault();
            $('#form-wrapper').load('{% url "laboratory_test" patient_id %}');
        });
        $(function(){
            $('*[class=datepicker]').appendDtpicker({"closeOnSelected": true, "dateOnly": true});
        });
    </script>
</div>

templates/patient/menstrual_history.html
{% load i18n %}

<div id="form-wrapper">
    {% include "_inner_message.html" %}
    <form action="" method="POST" id="form-base">
        {% csrf_token %}
        <table class="table table-hover table-striped">
            <tr>
                <td {% if medical_tab == 'fmh' %}class="medical-active"{% endif %}><a class="medical-link" href="{% url 'medical_history' patient_id %}">Family Medical History</a></td>
                <td>
                </td>
            </tr>
            <tr>
                <td {% if medical_tab == 'pah' %}class="medical-active"{% endif %}><a class="medical-link" href="{% url 'past_medical_history' patient_id %}">Past Medical History</a></td>
                <td>
                </td>
            </tr>
            <tr>
                <td {% if medical_tab == 'meh' %}class="medical-active"{% endif %}>Menstrual History</td>
                <td>
                    <table class="table table-normal">
                        {% for f in form %}
                            <tr>
                                <td><label for="id_{{ f.name }}">{{ f.label }}</label></td>
                                <td>{{ f }}
                                    <div class="control-group{% if f.errors %} error{% endif %}">
                                        {% if f.errors %}
                                            <span class="help-inline">{{ f.errors }}</span>
                                        {% endif %}
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                        <tr>
                            <td></td>
                            <td class="text-center">
                                <button type="submit" class="btn btn-inverse">{% trans "Save" %} &nbsp;<i class="icon-ok icon-white"></i></button>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr>
                <td {% if medical_tab == 'obh' %}class="medical-active"{% endif %}><a class="medical-link" href="{% url 'obstetric_history' patient_id %}">Obstetric History</a></td>
                <td>
                </td>
            </tr>
            <tr>
                <td {% if medical_tab == 'prh' %}class="medical-active"{% endif %}><a class="medical-link" href="{% url 'present_medical_history' patient_id %}">Present Medical History</a></td>
                <td>
                </td>
            </tr>
            <tr>
                <td {% if medical_tab == 'gyh' %}class="medical-active"{% endif %}><a class="medical-link" href="{% url 'gynaecological_history' patient_id %}">Gynaecological History</a></td>
                <td></td>
            </tr>
            <tr>
                <td {% if medical_tab == 'imh' %}class="medical-active"{% endif %}><a class="medical-link" href="{% url 'immunization_history' patient_id %}">Immunization History</a></td>
                <td></td>
            </tr>
        </table>
    </form>

    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.simple-dtpicker.js"></script>
    <script type="text/javascript">
        $('#form-base').submit(function(e) {
            e.preventDefault();
            $.post("{% url 'menstrual_history' patient_id %}", $("#form-base").serialize(), function(data) {
                $('#form-wrapper').html(data);
            });
        });
        $('*[class=datepicker]').appendDtpicker({"closeOnSelected": true, "dateOnly": true});
        $('.medical-link').click(function(e){
            e.preventDefault();
            $('#form-wrapper').load(this.getAttribute('href'));
        });
    </script>
</div>

templates/patient/patient_admission_view.html
{% load i18n %}

<div id="form-wrapper">
    {% include "_inner_message.html" %}
    <table class="table table-normal">
        <tr>
            <td>Hospital Name:</td>
            <td>{{ admission.hospital_name }}</td>
        </tr>
        <tr>
            <td>Date of admission:</td>
            <td>{{ admission.date_of_admission }}</td>
        </tr>
        <tr>
            <td>Date of discharge:</td>
            <td>{{ admission.date_of_discharge }}</td>
        </tr>
        <tr>
            <td></td>
            <td class="text-center">
                <button type="button" class="btn btn-primary" id="back-visit"><i class="icon-step-backward icon-white"></i> &nbsp;&nbsp;&nbsp;{% trans "Back" %}</button>
            </td>
        </tr>
    </table>

    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.min.js"></script>
    <script type="text/javascript">
        $('#back-visit').click(function(e) {
            e.preventDefault();
            $('#form-wrapper').load('{% url "patient_visit" patient_id %}');
        });
    </script>
</div>

templates/patient/ultrasound_scanning_add.html
{% load i18n %}

<div id="form-wrapper">
    {% include "_inner_message.html" %}
    <form action="" method="POST" id="form-upload" enctype="multipart/form-data">
        <table class="table table-hover table-normal">
            <tr>
                <td></td>
                <td id="img-td">{% if image %}<img src="{{ image }}" alt="Ultrasound Scan Image" class="ultrasound-img" width="200" />{% endif %}</td>
            </tr>
            <tr>
                <td><label class="control-label" for="image_file">Upload Image <span class="red"> *</span></label></td>
                <td><input type="file" name="image_file" id="image_file" onchange="fileSelected();" />
                    <div id="img-error" class="control-group error" style="display: none;">
                        <span class="help-inline"><b>Invalid image</b></span>
                    </div>
                    <div id="no-img-error" class="control-group error" style="display: none;">
                        <span class="help-inline"><b>No image selected</b></span>
                    </div>
                </td>
            </tr>
            <tr>
                <td></td>
                <td class="text-center">
                    <button type="submit" class="btn btn-inverse">{% trans "Upload" %} &nbsp;<i class="icon-ok icon-white"></i></button>
                </td>
            </tr>
        </table>
    </form>
    <form action="" method="POST" id="form-base" enctype="multipart/form-data">
        {% csrf_token %}
        <table class="table table-hover table-normal">
            {% for f in form %}
                {% include '_table_horizontal_field.html' with field=f %}
            {% endfor %}
            <tr>
                <td></td>
                <td class="text-center">
                    <button type="button" class="btn btn-primary" id="back-scan"><i class="icon-step-backward icon-white"></i> &nbsp;&nbsp;&nbsp;{% trans "Cancel" %}</button>
                    <button type="submit" class="btn btn-inverse">{% trans "Save" %} &nbsp;<i class="icon-ok icon-white"></i></button>
                </td>
            </tr>
        </table>
    </form>

    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.simple-dtpicker.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            if ($('#id_temp_img').val() != '') {
                set_temp_img($('#id_temp_img').val());
            };
        });

        $('#form-base').submit(function(e) {
            e.preventDefault();
            {% if us_id %}
            $.post("{% url 'ultrasound_scanning_view' patient_id us_id %}", $("#form-base").serialize(), function(data) {
                $('#form-wrapper').html(data);
            });
            {% else %}
            $.post("{% url 'ultrasound_scanning_add' patient_id %}", $("#form-base").serialize(), function(data) {
                $('#form-wrapper').html(data);
            });
            {% endif %}
        });
        $('#back-scan').click(function(e) {
            e.preventDefault();
            $('#form-wrapper').load('{% url "ultrasound_scanning" patient_id %}');
        });
        $(function(){
            $('*[class=datepicker]').appendDtpicker({"closeOnSelected": true, "dateOnly": true});
        });

        $('#form-upload').submit(function(e) {
            e.preventDefault();
            upload(document.getElementById('image_file'), '{% url "ultrasound_upload_image" %}');
        });

        function upload(field, upload_url) {
            if (field.files.length == 0) {
                $('#no-img-error').show();
                return;
            }
            file = field.files[0];
            var formdata = new FormData();
            formdata.append('file_upload', file);
            formdata.append('scan', {% if scan %}{{ scan.id }}{% else %}0{% endif %});
            $.ajax({
                url: upload_url,
                type: 'POST',
                data: formdata,
                processData: false,
                contentType: false,
                success: function(data) {set_temp_img(data)}
            });
        };

        function set_temp_img(data) {
            $('#img-td').load('/patient/ultrasound-scanning/img/'+ data +'/');
            $('#id_temp_img').val(data);
        };

        function fileSelected() {
            $('#img-error').hide();
            $('#no-img-error').hide();

            // get selected file element
            var oFile = document.getElementById('image_file').files[0];

            // filter for image files
            var rFilter = /^(image\/jpg|image\/jpeg|image\/png)$/i;
            if (! rFilter.test(oFile.type)) {
                $('#img-error').show();
                return;
            }
        };
    </script>
</div>