account/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url

urlpatterns = patterns('account.views',
    url(r'^login/$', 'account_login', name="account_login"),
    url(r'^logout/$', 'account_logout', name="account_logout"),
)

irpmemr/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:

    # # url(r'^irpmemr/', include('irpmemr.foo.urls')),
    # url(r'^admission/', 'irpmemr.views.admission', name='admission'),

    # url(r'^allpatients/', 'irpmemr.views.allpatients', name='allpatients'),

    # url(r'^addiinfo/(?P<pid>\w+)$', 'irpmemr.views.addiinfo', name='addiinfo'),

    # url(r'^medhis/(?P<pid>\w+)$', 'irpmemr.views.medhis', name='medhis'),

    # url(r'^routinecheckup/(?P<pid>\w+)$', 'irpmemr.views.routinecheckup', name='routinecheckup'),

    # url(r'^labtest/(?P<pid>\w+)$', 'irpmemr.views.labtest', name='labtest'),

    # url(r'^usscanning/(?P<pid>\w+)$', 'irpmemr.views.usscanning', name='usscanning'),

    # url(r'^notification$', 'irpmemr.views.notification', name='notification'),

    # url(r'^teleconsultation$', 'irpmemr.views.teleconsultation', name='teleconsultation'),

    # url(r'^setlogin$', 'irpmemr.views.setlogin', name='setlogin'),

    # url(r'^msg/add/$', 'irpmemr.views.addmessages', name='addmessages'),
    # url(r'^msg/show/$', 'irpmemr.views.showmessages', name='showmessages'),
    # url(r'^msg$', 'irpmemr.views.messages', name='messages'),

    url(r'^account/', include('account.urls')),
    url(r'^patient/', include('patient.urls')),
    url(r'^teleconsultation/', include('consultation.urls')),
    url(r'^notification/', include('notification.urls')),
    url(r'^$', 'irpmemr.views.home', name='home'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True,}),
)

urlpatterns += staticfiles_urlpatterns()

notification/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url

urlpatterns = patterns('notification.views',
    url(r'^$', 'notification', name="notifications"),
)

admission/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.core.urlresolvers import reverse

from irpmemr.models import CommonModel

class PatientVisit(CommonModel):
    patient = models.OneToOneField('patient.PatientInformation')
    first_visit = models.DateTimeField(null=True, blank=True)
    second_visit = models.DateTimeField(null=True, blank=True)
    third_visit = models.DateTimeField(null=True, blank=True)
    fourth_visit = models.DateTimeField(null=True, blank=True)
    fifth_visit = models.DateTimeField(null=True, blank=True)
    other_visit = models.DateTimeField(null=True, blank=True)

    def __unicode__(self):
        return str(self.patient.get_fullname())

class HospitalAdmission(CommonModel):
    patient = models.ForeignKey('patient.PatientInformation')
    hospital_name = models.CharField(max_length=50)
    date_of_admission = models.DateTimeField("Date of admission")
    date_of_discharge = models.DateTimeField("Date of discharge")

    def __unicode__(self):
        return str(self.patient.get_fullname())

    def get_absolute_url(self):
        return reverse('patient_admission_view', args=[self.patient.id, self.id])

notification/models.py
from django.db import models

# Create your models here.

admission/forms.py
# -*- coding: utf-8 -*-

from django import forms

from admission.models import PatientVisit, HospitalAdmission

VISIT_LIST = ['first_visit', 'second_visit', 'third_visit', 'fourth_visit', 'fifth_visit', 'other_visit']

class PatientVisitForm(forms.ModelForm):
    """
    Form for PatientVisit
    """
    first_visit = forms.DateTimeField(widget=forms.TextInput(attrs={'class':'null-date'}), required=False)
    second_visit = forms.DateTimeField(widget=forms.TextInput(attrs={'class':'null-date'}), required=False)
    third_visit = forms.DateTimeField(widget=forms.TextInput(attrs={'class':'null-date'}), required=False)
    fourth_visit = forms.DateTimeField(widget=forms.TextInput(attrs={'class':'null-date'}), required=False)
    fifth_visit = forms.DateTimeField(widget=forms.TextInput(attrs={'class':'null-date'}), required=False)
    other_visit = forms.DateTimeField(widget=forms.TextInput(attrs={'class':'null-date'}), required=False)

    class Meta:
        model = PatientVisit
        exclude = ('patient',)

    def __init__(self, *args, **kwargs):
        super(PatientVisitForm, self).__init__(*args, **kwargs)
        instance = kwargs.get('instance')
        if instance:
            for i in VISIT_LIST:
                if instance.__dict__.get(i):
                    self.fields[i].widget = forms.TextInput(attrs={'class':'datetimepicker'})


class PatientAdmissionForm(forms.ModelForm):
    """
    Form for HospitalAdmission
    """
    date_of_admission = forms.DateTimeField(widget=forms.TextInput(attrs={'class':'datetimepicker'}))
    date_of_discharge = forms.DateTimeField(widget=forms.TextInput(attrs={'class':'datetimepicker'}))

    class Meta:
        model = HospitalAdmission
        exclude = ('patient',)

patient/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.db.models import Q

from patient.models import PatientInformation, AdditionalPatientInformation, Guardian, \
    MedicalHistory, PastMedicalHistory, PresentMedicalHistory, FamilyMedicalHistory, \
    MenstrualHistory, ObstetricHistory, GynaecologicalHistory, ImmunizationHistory, \
    Routinecheckup, LaboratoryTest, UltrasoundScanning, Prescription, PreviousObstetricHistory, \
    PreviousSurgery

class SearchPatientForm(forms.Form):
    q = forms.CharField(label="Search", required=True)

    def results(self):
        """
        Filter the results from PatientInformation
        """
        q = self.cleaned_data['q'].strip()
        patients = PatientInformation.objects.filter(Q(operator__username__contains=q) | \
            Q(patient_id__contains=q) | Q(first_name__contains=q) | Q(last_name__contains=q) | \
            Q(email__contains=q)).distinct()
        return patients

class AddPatientForm(forms.ModelForm):
    """
    Form for add new patient
    """
    date_of_birth = forms.DateField(widget=forms.TextInput(attrs={'class':'datepicker'}))

    class Meta:
        model = PatientInformation

class PatientInformationForm(forms.ModelForm):
    """
    Form for view or edit patient info
    """
    date_of_birth = forms.DateField(widget=forms.TextInput(attrs={'class':'datepicker'}))

    class Meta:
        model = PatientInformation
        exclude = ('patient',)

class AdditionalPatientInformationForm(forms.ModelForm):
    """
    Form for view or edit additional patient info
    """
    # def __init__(self, patient=None, *args, **kwargs):
    #     super(AdditionalPatientInformationForm, self).__init__(*args, **kwargs)
    #     if patient:
    #         self.fields['patient'].initial = patient.id
    #         self.fields['patient'].widget.attrs['disabled'] = True

    class Meta:
        model = AdditionalPatientInformation
        exclude = ('patient',)

class GuardianForm(forms.ModelForm):
    """
    Form for view or edit guardian info
    """
    # def __init__(self, patient=None, *args, **kwargs):
    #     super(GuardianForm, self).__init__(*args, **kwargs)
    #     if patient:
    #         self.fields['patient'].initial = patient.id
    #         self.fields['patient'].widget.attrs['disabled'] = True

    class Meta:
        model = Guardian
        exclude = ('patient',)

class MedicalHistoryForm(forms.ModelForm):
    """
    form for MedicalHistory
    """
    class Meta:
        model = MedicalHistory
        exclude = ('patient',)

class PastMedicalHistoryForm(forms.ModelForm):
    """
    form for PastMedicalHistory
    """
    date = forms.DateField(widget=forms.TextInput(attrs={'class':'datepicker'}))

    class Meta:
        model = PastMedicalHistory
        exclude = ('patient',)

class PresentMedicalHistoryForm(forms.ModelForm):
    """
    form for PresentMedicalHistory
    """
    date = forms.DateField(widget=forms.TextInput(attrs={'class':'datepicker'}))
    class Meta:
        model = PresentMedicalHistory
        exclude = ('patient',)

class FamilyMedicalHistoryForm(forms.ModelForm):
    """
    form for FamilyMedicalHistory
    """
    date = forms.DateField(widget=forms.TextInput(attrs={'class':'datepicker'}))
    class Meta:
        model = FamilyMedicalHistory
        exclude = ('patient',)

class MenstrualHistoryForm(forms.ModelForm):
    """
    form for MenstrualHistory
    """
    day_of_visit = forms.DateField(widget=forms.TextInput(attrs={'class':'datepicker'}))
    last_menstrual_periods = forms.DateField(widget=forms.TextInput(attrs={'class':'datepicker'}))
    expected_date_of_delivery = forms.DateField(widget=forms.TextInput(attrs={'class':'datepicker'}))
    class Meta:
        model = MenstrualHistory
        exclude = ('patient',)

class ObstetricHistoryForm(forms.ModelForm):
    """
    form for ObstetricHistory
    """
    class Meta:
        model = ObstetricHistory
        exclude = ('patient',)

class PreviousObstetricHistoryForm(forms.ModelForm):
    """
    form for PreviousObstetricHistory
    """
    dob = forms.DateField(widget=forms.TextInput(attrs={'class':'datepicker'}))
    class Meta:
        model = PreviousObstetricHistory
        exclude = ('patient',)

class GynaecologicalHistoryForm(forms.ModelForm):
    """
    form for GynaecologicalHistory
    """
    date_of_last_pap_smear = forms.DateField(widget=forms.TextInput(attrs={'class':'datepicker'}))
    class Meta:
        model = GynaecologicalHistory
        exclude = ('patient', 'previous_surgery',)

class ImmunizationHistoryForm(forms.ModelForm):
    """
    form for ImmunizationHistory
    """
    tetanus_toxoid1 = forms.DateTimeField(label="First Injection", widget=forms.TextInput(attrs={'class':'datetimepicker'}), required=False)
    tetanus_toxoid2 = forms.DateTimeField(label="Second Injection", widget=forms.TextInput(attrs={'class':'null-date'}), required=False)
    tetanus_toxoid3 = forms.DateTimeField(label="Third Injection", widget=forms.TextInput(attrs={'class':'null-date'}), required=False)

    class Meta:
        model = ImmunizationHistory
        exclude = ('patient',)

    def __init__(self, *args, **kwargs):
        super(ImmunizationHistoryForm, self).__init__(*args, **kwargs)
        instance = kwargs.get('instance')
        if instance:
            for i in ['tetanus_toxoid2', 'tetanus_toxoid3']:
                if instance.__dict__.get(i):
                    self.fields[i].widget = forms.TextInput(attrs={'class':'datetimepicker'})

class RoutinecheckupForm(forms.ModelForm):
    """
    form for Routinecheckup
    """
    date = forms.DateField(widget=forms.TextInput(attrs={'class':'datepicker'}))
    class Meta:
        model = Routinecheckup
        exclude = ('patient',)

class LaboratoryTestForm(forms.ModelForm):
    """
    form for LaboratoryTest
    """
    date = forms.DateField(widget=forms.TextInput(attrs={'class':'datepicker'}))
    class Meta:
        model = LaboratoryTest
        exclude = ('patient',)

class UltrasoundScanningForm(forms.ModelForm):
    """
    form for UltrasoundScanning
    """
    date = forms.DateField(widget=forms.TextInput(attrs={'class':'datepicker'}))
    temp_img = forms.CharField(widget=forms.HiddenInput())
    class Meta:
        model = UltrasoundScanning
        exclude = ('patient',)

class PrescriptionForm(forms.ModelForm):
    """
    form for Prescription
    """
    date = forms.DateField(widget=forms.TextInput(attrs={'class':'datepicker'}))
    class Meta:
        model = Prescription
        exclude = ('patient',)

class PreviousSurgeryForm(forms.ModelForm):
    """
    form for PreviousSurgery
    """
    class Meta:
        model = PreviousSurgery
        exclude = ('patient',)

admission/views.py
# Create your views here.

templates/_horizontal_field.html
{% load i18n %}
{% if field.is_hidden %}
    {{ field }}
{% else %}
    <div class="control-group{% if field.errors %} error{% endif %}">
        <label class="control-label" for="id_{{ field.name }}">{{ field.label }} {% if field.field.required %}<span class="red"> *</span>{% endif %}</label>
        <div class="controls">
            {{ field }}
            {% if field.help_text %}
                <br /><span class="help-inline">{{ field.help_text }}</span>
            {% endif %}
            {% if field.errors %}
                <br /><span class="help-inline">{{ field.errors }}</span>
            {% endif %}
        </div>
    </div>
{% endif %}

templates/_inner_message.html
{% if messages %}
    <section id="messages">
        <div class="container">
            <div class="row">
                <div class="span11">
                    {% for message in messages %}
                        <div class="alert alert-{% if message.tags %}{{ message.tags }}{% else %}error{% endif %}">
                            <a class="close" data-dismiss="alert" href="#">×</a>
                            {{ message|safe }}
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
{% endif %}

templates/_table_horizontal_field.html
{% load i18n %}
{% if field.is_hidden %}
    {{ field }}
{% else %}
    <tr>
        <td><label class="control-label" for="id_{{ field.name }}">{{ field.label }} {% if field.field.required %}<span class="red"> *</span>{% endif %}</label></td>
        <td>{{ field }}
            <div class="control-group{% if field.errors %} error{% endif %}">
                {% if field.errors %}
                    <span class="help-inline">{{ field.errors }}</span>
                {% endif %}
            </div>
        </td>
    </tr>
{% endif %}

templates/addiinfo.html
{% extends "base.html" %}
{% load static %}{% load i18n %}
{% block title %} Home {% endblock %}

{% block content %}
<div style="float:right;"><a href="/admin/irpmemr/additionalpatientinformation/add/">Add Additional Patient Info</a></div>



<div class="allpatients">
	{% if api %}
	
	{% for b in bpi %}
		<p><span style="font-weight:bold;">Patient Info : {{b.name}}</span></p>
		<p>Date of Birth: {{b.date_of_birth}}</p>
	{% endfor %}
	
	{% for p in api %}
		<p>Cigarettes : {{p.cigarettes}}{% if p.cigarettes %} <img height="20px;" src="{% get_static_prefix %}/images/important2.png" /> {% endif %}</p>
		<p>Alcohol : {{p.alcohol}}{% if p.alcohol %} <img height="20px;" src="{% get_static_prefix %}/images/important2.png" /> {% endif %}</p>
		<p>Literate : {{p.literate}}</p>
		<p>Educational Level : {{p.educational_level}}</p>
		<p>Occupation : {{p.occupation}}</p>
	{% endfor %}
	
	{% else %}
		<p>There is no data in additional patient information</p>
	{% endif %}
</div>

<div class="allpatients">
<div style="float:right;"><a href="/admin/irpmemr/guardian/add/">Add Guardian Info</a></div>
	{% if grd %}
	
	{% for p in grd %}
		<p><span style="font-weight:bold;"> Guardian </span></p>
		<p>Relation: {{p.relation}}</p>
		<p>First name: {{p.first_name}}</p>
		<p>Last name: {{p.last_name}}</p>
		<p>Contact number: {{p.contact_number}}</p>
		<p>Home Address: {{p.home_address}}</p>
		<p>Job: {{p.job}}</p>
		<p>Educational Level : {{p.educational_level}}</p>	
	{% endfor %}
	
	
	{% else %}
		<p>There is no data in Guardian information</p>
	{% endif %}
	
	
</div>


{% endblock %}

templates/admission.html
{% extends "base.html" %}
{% load static %}{% load i18n %}
{% block title %} Home {% endblock %}

{% block content %}

<script type="text/javascript">

$(document).ready(function() {
    $('#setable').dataTable();
    
} );
		
</script>

<div style="float:none;"><a href="/admin/irpmemr/patientadmission/add/">Add Patient Admission</a></div>
{% if pa %}
	<table cellpadding="0" cellspacing="0" border="0" class="display" width="100%" id="setable">
		<thead>
			<tr>
				<th>Name</th>
				<th>First Visit</th>
				<th>Second Visit</th>
				<th>Third Visit</th>
				<th>Fourth Visit</th>
				<th>Other Visit</th>
				<th>Hospital Name</th>
				<th>Date Of Admission</th>
				<th>Date Of Discharge</th>
			</tr>
		</thead>
		<tfoot>
			<tr>
				<th>Name</th>
				<th>First Visit</th>
				<th>Second Visit</th>
				<th>Third Visit</th>
				<th>Fourth Visit</th>
				<th>Other Visit</th>
				<th>Hospital Name</th>
				<th>Date Of Admission</th>
				<th>Date Of Discharge</th>
			</tr>
		</tfoot>
		<tbody>
	{% for p in pa %}
		<tr>
			<td>{{p.pid}}</td>
			<td>{{p.first_visit}}</td>
			<td>{{p.second_visit}}</td>
			<td>{{p.third_visit}}</td>
			<td>{{p.fourth_visit}}</td>
			<td>{{p.other_visit}}</td>
			<td>{{p.hospital_name}}</td>
			<td>{{p.date_of_admission}}</td>
			<td>{{p.date_of_discharge}}</td>
			
		</tr>
	{% endfor %}
	</tbody>
	</table>
	{% else %}
		<p>There is no data</p>
	{% endif %}

{% endblock %}

templates/base.html
{% load i18n %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}"{% if LANGUAGE_BIDI %} dir="rtl"{% endif %}>
    <head>
        <meta charset="utf-8">
	   {% comment %}<script type="text/javascript" src="http://cdn.dev.skype.com/uri/skype-uri.js"></script>{% endcomment %}
        <title>{% block title %}{% endblock title %} | {{ site.name }}</title>

        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% block meta %}
        {% endblock meta %}
        <meta name="author" content="Azri Anuar">

        <link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap.min.css">
        <link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap-responsive.min.css">
        <link rel="stylesheet" href="{{ STATIC_URL }}css//jquery-ui.css">
        <link type="text/css" href="{{ STATIC_URL }}css/jquery.simple-dtpicker.css" rel="stylesheet" />
        <link rel="stylesheet" href="{{ STATIC_URL }}css/style.css" type="text/css" media="screen, projection">
        {% block css %}{% endblock css %}

        <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
            <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <link rel="shortcut icon" href="{{ STATIC_URL }}ico/favicon.ico">
    </head>
    <body>
        {% block header %}
        <section id="header">
            <div class="container">

                <div class="navbar">
                    <div class="navbar-inner">
                        <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                            <span class="pull-left" style="padding-top:1px;">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </span>
                            <span class="pull-right" style="color:#555; font-size:12px; margin-left:15px; text-shadow:none;">{% trans 'Menu' %}</span>
                        </button>

                        <div class="row">
                            <div class="span2">
                                <a class="brand" href="{% url 'home' %}">
                                    <img src="{{ STATIC_URL }}img/logo-irpm.png" alt="{{ site.name }}" />
                                </a>
                            </div>
                            <div class="span10 web-menu">
                                <div class="nav-collapse collapse pull-left">
                                    <ul class="nav">
                                        {% include '_menu.html' %}
                                    </ul>
                                </div>
                            </div>
                        </div>

                        <div class="row mobile-menu">
                            <div class="span12">
                                <div class="nav-collapse collapse">
                                    <ul class="nav">
                                        {% include '_menu.html' %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        {% endblock header %}

        {% block messages %}
            {% if messages %}
                <section id="messages">
                    <div class="container">
                        <div class="row">
                            <div class="span12">
                                {% for message in messages %}
                                    <div class="alert alert-{% if message.tags %}{{ message.tags }}{% else %}error{% endif %}">
                                        <a class="close" data-dismiss="alert" href="#">×</a>
                                        {{ message|safe }}
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </section>
            {% endif %}
        {% endblock messages %}

        {% block content %}{% endblock content %}

        {% block footer %}
        <footer>
            <div class="container">
                <div class="row">
                    <div class="span12 text-center">
                        &copy; {{ CURRENT_YEAR }} | <a href="{% url 'home' %}">{{ site.name }}</a><br>
                        <!-- Developed by LEHFO -->
                    </div>
                </div>
            </div>
        </footer>
        {% endblock footer %}

        <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.min.js"></script>
        <script type="text/javascript" src="{{ STATIC_URL }}js/jquery-ui.min.js"></script>
        <script type="text/javascript" src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
        <script type="text/javascript">
            $(document).ready(function() {

            });
        </script>
        {% block bottom_javascript %}
            <script type="text/javascript">
                $(document).ready(function() {

                });
            </script>
        {% endblock bottom_javascript %}
    </body>
</html>

templates/home.html
{% extends "base.html" %}
{% load static %}{% load i18n %}
{% block title %} Home {% endblock %}

{% block content %}
    <section id="page-content">
        <div class="container">
            <div class="row">
                <div class="span12">
                    <div class="page-header mt0">
                        <h2>{% trans 'Home Page' %}</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="span12">
                    <form action="" method="POST" class="pull-right">
                        {% csrf_token %}
                        <div class="input-append">
                            <input class="span2" id="id_q" name="q" type="text" {% if is_search %}value={{ is_search }}{% endif %} float="left">
                            <button type="submit" class="btn" type="button">Search</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="row">
                <div class="span12">
                    <table class="table table-bordered table-hover table-striped">
                        <tr>
                            <th>{% trans "ID" %}</th>
                            <th>{% trans "Full Name" %}</th>
                            <th>{% trans "Age" %}</th>
                        </tr>
                        {% for patient in patients %}
                            <tr>
                                <td><a href="{{ patient.get_absolute_url }}">{{ patient.patient_id }}</a></td>
                                <td><a href="{{ patient.get_absolute_url }}"><i class="icon-user"></i> &nbsp;{{ patient.get_fullname }}</a></td>
                                <td>{{ patient.get_age }}</td>
                            </tr>
                        {% empty %}
                            {% if is_search %}
                                <tr>
                                    <td colspan="3">No results found</td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                    </table>
                    <div class="form-actions" align="right">
                        <button type="button" class="btn btn-primary" id="add-patient" onclick="location.href='{% url "patient_add" %}';">{% trans "Add new patient" %} &nbsp;&nbsp;&nbsp;<i class="icon-play icon-white"></i></button>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/immunizationhis.html
{% extends "base.html" %}
{% load static %}{% load i18n %}
{% block title %} Home {% endblock %}

{% block content %}
<div style="float:right;"><a href="/admin/irpmemr/immunizationhistory/add/">Add Immunization History</a></div>

<div class="allpatients">
	{% if immun %}
	{% for p in immun %}
		<p>Name: {{p.pid}}</p>
		<p>Vaccination: {{p.vaccination}}</p>
		<p>First Injection: {{p.tetanus_toxoid1}}</p>
		<p>Second Injection : {{p.tetanus_toxoid2}}</p>
		<p>Third Injection : {{p.tetanus_toxoid3}}</p>
	{% endfor %}
	
	{% else %}
		<p>No immunization record available</p>
	{% endif %}
</div>

{% endblock %}

templates/messages.html
{% extends "base.html" %}
{% load static %}{% load i18n %}
{% block title %} Home {% endblock %}

{% block content %}
<div id="chatbody">
		<div id="messagebody"></div>
	</div>
	
	<div id="chatform">
		<script type="text/javascript">
			$(document).ready(function() {
				var tmp = window.location.href;
				
				function getMessages() {
					$.ajax({
						url: tmp + '/show',
						data: {
							rev: 'hello',
						},
						success: function(response, status) {
							//alert(response);
							var p = "";
							for(i = 0; i < response.length; i++) {
								p += "<p>Sender:" + response[i]['sender'] + " Receiver:" + response[i]['receiver'] + "<br/>Body:" + response[i]['body'] + "</p>"
								$('#messagebody').html(p);
							}
						}
					});
				}
				
				var auto_refresh = setInterval(function() {
					getMessages();
				}, 5000);
				
				$('#button').click(function() {
					getMessages();
				});
				
				$('#msgend').click(function() {
					var rev = $('#receiver').val();
					var mbody = $('#msgbody').val();
					
					$.ajax({
						type: "POST",
						url: tmp + '/add/',
						data: {
							receiver: rev,
							msgbody:mbody,
							csrfmiddlewaretoken: '{{ csrf_token }}'
						},
						success: function(response, status) {
							$('#msgbody').val('');
						}
					});
					
					return false;
				});
			});
		</script>
		<form id="form1" method="post" action="">
		{% csrf_token %}
			<select name="receiver" id="receiver">
				{% for u in users %}
					<option value="{{u}}">{{u}}</option>
				{% endfor %}
			</select>
			<label>
				Send a message:
				<textarea rows="3" cols="20" name="msgbody" id="msgbody"></textarea>
			</label>
			<input type="button" name="submit" value="send" id="msgend"/>		
		</form>
	</div>
	<li><a href="/medhis/{{p.id}}">Report</a></li>
	<li><a href="{{ROOT}}/teleconsultation">{% trans "Teleconsultation with specialist" %}</a></li>
{% endblock %}